# -*- coding: utf-8 -*-
"""Sort, rename and catalog the PDF library under d:/READING/Books."""
import os, re, json, shutil, unicodedata

BASE = r"d:/READING/Books"

CATS = {
 1:"01 - Marxist and Critical Theory Classics",
 2:"02 - Marx-Engels Collected Works (MECW)",
 3:"03 - Maoism and Peoples War",
 4:"04 - Indian Communist and Naxalite Movement",
 5:"05 - Caste, Dalit and Social Justice",
 6:"06 - Kashmir",
 7:"07 - Palestine and West Asia",
 8:"08 - History, State and Politics",
 9:"09 - Political Economy and Globalization",
 10:"10 - Ecology, Science and Society",
 11:"11 - Literature and the Arts",
 12:"12 - Biography and Memoir",
 13:"13 - Bangladesh - History and Politics",
 14:"14 - Feminism and Gender",
 15:"15 - Cybersecurity and Hacking",
 16:"16 - Periodicals, Pamphlets and Reports",
 99:"00 - Duplicates",
}

# (relative_path, category, title, language, genre, description)
E = [
("'গান্ধীবাদের_স্বরূপ'.pdf",8,"গান্ধীবাদের স্বরূপ (The Nature of Gandhism)","Bengali","Political essay","Critical Marxist examination of Gandhian ideology and its class character."),
("'দ্রৌপদী'.pdf",11,"দ্রৌপদী — মহাশ্বেতা দেবী (Draupadi)","Bengali","Short story","Mahasweta Devi's iconic story of Dopdi Mejhen, a Santhal woman insurgent defiant under custodial torture."),
("'মানবা‌ধিকার_ও_রবীন্দ্রনাথ'.pdf",8,"মানবাধিকার ও রবীন্দ্রনাথ (Human Rights and Tagore)","Bengali","Essay","Reading the idea of human rights through Rabindranath Tagore's thought."),
("'মার্কসবাদ_লেনিনবাদ_মাওবাদ'.pdf",3,"মার্কসবাদ লেনিনবাদ মাওবাদ (Marxism-Leninism-Maoism)","Bengali","Political theory","Bengali primer on the synthesised doctrine of Marxism-Leninism-Maoism."),
("14a47202-9901-4f88-859c-0a690a8060a5.pdf",6,"Of Gardens and Graves - Kashmir, Poetry, Politics - Suvir Kaul","English","Essays and poetry","Essays plus translated Kashmiri poems on militarisation, grief and politics in the Valley."),
("1948-political-thesis.pdf",4,"Political Thesis 1948 - Communist Party of India","English","Party document","The CPI's 1948 (Ranadive-line) thesis calling for armed insurrection after independence."),
("2015.265042.Shat-sattare-Nadiya.pdf",4,"সাতে সত্তরে নদীয়া (Nadia in the Seventies)","Bengali","History","Local history of the Naxalite upsurge and state repression in Nadia district, West Bengal, in the 1970s."),
("2015.266191.Babar.pdf",11,"বাবর (Babar)","Bengali","Bengali book","Bengali volume digitised from a National Library scan; subject not recorded in the file metadata."),
("2015.266384.Perute-Surya.pdf",3,"পেরুতে সূর্য (Sun Over Peru)","Bengali","History","Bengali account of the Communist Party of Peru and the Peruvian people's war."),
("2015.301655.Warly-Krishakder.pdf",4,"ওয়ারলি কৃষকদের বিদ্রোহ (The Warli Peasants' Revolt)","Bengali","History","History of the Warli adivasi peasant revolt led by communists in 1940s Maharashtra."),
("2015.455695.May-Dibaser.pdf",16,"মে দিবসের ইতিহাস (History of May Day)","Bengali","History","Bengali pamphlet on the origins and history of International Workers' Day."),
("2020.pdf",16,"Peasant Agitation Against Farm Acts - Not Their Fight Alone (RUPE)","English","Pamphlet","RUPE pamphlet on the 2020-21 farmers' movement against the three farm laws."),
("20210721en-1.pdf",16,"Ang Bayan - 21 July 2021 (CPP)","English","Periodical","English edition of Ang Bayan, organ of the Communist Party of the Philippines."),
("210621en.pdf",16,"Ang Bayan - 21 June 2021 (CPP)","English","Periodical","English edition of Ang Bayan, organ of the Communist Party of the Philippines."),
("28-wppb-constitution.pdf",8,"Constitution of the Workers' and Peasants' Party of Bengal (1928)","English","Party document","The 1928 constitution of an early Indian left formation, the WPP of Bengal."),
("3cd26a8d-ad1f-4476-9597-ff2f9ddcd333.pdf",4,"Amar Bari Tomar Bari Naxalbari","English","History","Illustrated account of the Naxalbari uprising and its legacy."),
("4_6001355436173821841.pdf",6,"JKLF - Jammu Kashmir Ideology (Document I)","English","Pamphlet","Jammu Kashmir Liberation Front document on its nationalist ideology."),
("4_6014575461475026659.pdf",6,"JKLF - Jammu Kashmir Ideology (Document II)","English","Pamphlet","Jammu Kashmir Liberation Front statement of its ideology and aims."),
("4_6033066708728547307.pdf",6,"JKLF - Statement (Team JKLF)","English","Pamphlet","Short Jammu Kashmir Liberation Front published statement."),
("5_6053269070952792702.pdf",11,"Unidentified Bengali Volume I (banglabooks.in scan)","Bengali","Bengali book","Scanned Bengali book with no metadata or OCR text; subject not identifiable from the file."),
("5_6053269070952792703.pdf",11,"Unidentified Bengali Volume II (scan)","Bengali","Bengali book","Large scanned Bengali volume with no metadata or extractable text."),
("5_6062222321123329860.pdf",10,"Nature, Culture, Imperialism - Essays on the Environmental History of South Asia","English","Environmental history","Arnold and Guha (eds.) essays on the environmental history of South Asia."),
("5_6201607831083287076.pdf",13,"সিরাজ সিকদার রচনা - পূর্ববাংলা শ্রমিক আন্দোলনের সমালোচনা","Bengali","Political writing","Siraj Sikder's critique of the line of the East Bengal Workers' Movement."),
("5_6237820598731408433.pdf",11,"Unidentified Bengali Volume III (scan)","Bengali","Bengali book","Scanned Bengali document with no metadata or extractable text."),
("5_6255981717618688555.pdf",11,"Unidentified Bengali Volume IV (scan)","Bengali","Bengali book","Large scanned Bengali volume with no metadata or extractable text."),
("5_6287543967693144910.pdf",4,"Singur to Lalgarh via Nandigram - Amit Bhattacharyya","English","History","People's resistance to displacement at Singur, Nandigram and Lalgarh."),
("5_6318562268749496820.pdf",9,"Planet of Slums - Mike Davis","English","Urban studies","Mike Davis on explosive global slum growth and informal urban life under neoliberalism."),
("5_6321294383345828345.pdf",5,"Why Did the Brahmins Give Up Beef-Eating? - D. N. Jha","English","History","D. N. Jha on beef-eating in ancient India and the making of the sacred cow."),
("5_6332607352973296086.pdf",16,"কৃষক আন্দোলনের পঞ্চম ফ্রন্ট (Fifth Front of the Farmers' Movement)","Bengali","Pamphlet","Bengali pamphlet from the 2020-21 farmers' movement, voices from the Palwal border."),
("71 book.pdf",13,"একাত্তরের নিবন্ধ সংকলন ('71 - Collected Essays)","Bengali","Essays","Collection of essays on Bangladesh's 1971 Liberation War."),
("78711574-d908-4554-bd8f-d8f33b4c4eb8.pdf",6,"Paradise on Fire - Syed Ali Geelani and the Struggle for Freedom in Kashmir - Abdul Hakeem","English","Biography and politics","Biographical political account of Kashmiri leader Syed Ali Geelani."),
("@peopleslibrary_Bangla_Kabitar_Samuchhoy_1_by_Sukumar_Sen.pdf",11,"বাংলা কবিতার সমুচ্চয় ১ - সুকুমার সেন (Anthology of Bengali Poetry, Vol.1)","Bengali","Poetry anthology","Sukumar Sen's edited anthology of Bengali poetry, volume one."),
("@peopleslibrary_Bankocracy_web.pdf",9,"Bankocracy - Eric Toussaint","English","Political economy","Toussaint's critique of banks, debt and the 2008 financial crisis."),
("@peopleslibrary_Beginning_Ethical_Hacking_with_Kali_Linux_Computational.pdf",15,"Beginning Ethical Hacking with Kali Linux - Sanjib Sinha","English","Cybersecurity","Introductory guide to ethical hacking and penetration testing using Kali Linux."),
("@peopleslibrary_Biswasher-Virus-Ebook.pdf",10,"বিশ্বাসের ভাইরাস (The Virus of Belief)","Bengali","Rationalism","Bengali rationalist book challenging blind faith and superstition."),
("@peopleslibrary_Bondi_Jege_Achho_By_Sunil_Gangopadhyay.pdf",11,"বন্দী জেগে আছো - সুনীল গঙ্গোপাধ্যায় (Bondi Jege Achho)","Bengali","Poetry","Poetry collection by Sunil Gangopadhyay."),
("@peopleslibrary_Caste_Class_and_Politics_in_West_Bengal.pdf",5,"Caste, Class and Politics in West Bengal","English","Sociology","Study of the interlinkage of caste, class and politics in a West Bengal village."),
("@peopleslibrary_Enough Is Enough.pdf",9,"Enough Is Enough - Building a Sustainable Economy","English","Political economy","Tract for a steady-state, post-growth economy."),
("@peopleslibrary_Hacking Wireless Networks for Dummies(1).pdf",15,"Hacking Wireless Networks for Dummies - Beaver and Davis","English","Cybersecurity","Practical guide to testing and securing wireless networks."),
("@peopleslibrary_Hacking_Computer_Hacking,_Security_Testing,Penetration.pdf",15,"Hacking - Computer Hacking, Security and Penetration Testing - Gary Hall","English","Cybersecurity","Beginner's overview of hacking, security testing and basic wireless security."),
("@peopleslibrary_Idealism_as_Modernism_Hegelian_Variations_by_Robert.pdf",1,"Idealism as Modernism - Hegelian Variations - Robert Pippin","English","Philosophy","Pippin's essays defending Hegelian idealism as the core of philosophical modernity."),
("@peopleslibrary_Jhumur_O_Charjapod_by_Kiriti_Mahato.pdf",11,"ঝুমুর ও চর্যাপদ - কিরীটি মাহাত (Jhumur O Charyapad)","Bengali","Literary study","On Jhumur folk songs and the Charyapada, the earliest Bengali verse."),
("@peopleslibrary_kings of Kashmira_1.pdf",6,"Kings of Kashmira (Rajatarangini), Vol. 1 - Kalhana","English","History","English translation of Kalhana's classical chronicle of Kashmir's kings, vol.1."),
("@peopleslibrary_kings of Kashmira_3.pdf",6,"Kings of Kashmira (Rajatarangini), Vol. 3 - Kalhana","English","History","English translation of Kalhana's Rajatarangini, vol.3."),
("@peopleslibrary_olli-deep-dark-web.pdf",15,"The Surface, Deep and Dark Web (OLLI Presentation)","English","Cybersecurity","Introductory presentation on the surface web, deep web, dark web and bitcoin."),
("@peopleslibrary_southern india.pdf",8,"Southern India","English","History and travel","Early 20th-century descriptive volume on southern India."),
("@peopleslibrary_Sumaner_Gaan_8_by_Kabir_Suman.pdf",11,"সুমনের গান ৮ - কবীর সুমন (Sumaner Gaan 8)","Bengali","Songs and lyrics","Volume of song lyrics and notation by singer-songwriter Kabir Suman."),
("@peopleslibrary_The motorcycle dairy by Che Guevara.pdf",12,"The Motorcycle Diaries - Che Guevara","English","Memoir","Che Guevara's youthful travel diary across South America that shaped his politics."),
("@peopleslibrary_The_Basics_of_Hacking_and_Penetration_Testing,_Second.pdf",15,"The Basics of Hacking and Penetration Testing (2nd ed.) - Patrick Engebretson","English","Cybersecurity","Hands-on introduction to the penetration-testing workflow with Kali Linux."),
("@peopleslibrary_The_Dark_Secrets_of_the_Search_Engines_Find_out.pdf",15,"The Dark Secrets of the Search Engines - F. G. B. de Azevedo","English","Technology","Popular book on how search engines work and what they hide from users."),
("@peopleslibrary_The_Darkest_Web_Drugs,_death_and_destroyed_lives.pdf",15,"The Darkest Web - Eileen Ormsby","English","True crime and tech","Investigative account of dark-web drug markets, hitman scams and law enforcement."),
("@peopleslibrary_Towards_Understanding_Semi_Colonial_Semi_Feudal.pdf",9,"Towards Understanding Semi-Colonial Semi-Feudal India","English","Political economy","Essays theorising India as a semi-colonial, semi-feudal social formation."),
("@peopleslibrary_civilization of india.pdf",8,"The Civilization of India - Romesh Chunder Dutt","English","History","R. C. Dutt's classic survey of Indian civilisation."),
("@peopleslibrary_india pictorial and desciptive.pdf",8,"India, Pictorial and Descriptive","English","History and travel","Illustrated 19th-century descriptive account of India."),
("@peopleslibrary_je_golper_sesh_nei.pdf",11,"যে গল্পের শেষ নেই (The Story That Never Ends)","Bengali","Fiction","Bengali story collection / novel (scanned, no metadata)."),
("@peopleslibrary_চীন_সমাজতান্ত্রিক,_অর্থনীতির_বিকাশ.pdf",3,"চীন: সমাজতান্ত্রিক অর্থনীতির বিকাশ (China - Development of the Socialist Economy)","Bengali","Political economy","Bengali study of the development of the socialist economy in China."),
("@peopleslibrary_চে_স্মৃতিকথা_–_ফিদেল_কাস্ত্রো.pdf",12,"চে: স্মৃতিকথা - ফিদেল কাস্ত্রো (Che - A Memoir by Fidel Castro)","Bengali","Memoir","Fidel Castro's reminiscences of Che Guevara, in Bengali translation."),
("@peopleslibrary_সিরাজ_সিকদার_রচনা_পূর্ববাংলার_সমাজের_শ্রেণীবিশ্লেষণ.pdf",13,"সিরাজ সিকদার রচনা - পূর্ববাংলার সমাজের শ্রেণীবিশ্লেষণ (Class Analysis of East Bengal Society)","Bengali","Political writing","Siraj Sikder's class analysis of East Bengal (Bangladesh) society."),
("APRSU - A glorious saga of student struggle_organized.pdf",4,"APRSU - A Glorious Saga of Student Struggle","English","History","History of the Andhra Pradesh Radical Students' Union."),
("AWTW-06-AfghanRevolutionary.pdf",16,"A World to Win No.6 - An Afghan Revolutionary (SAMA)","English","Periodical","Interview with a SAMA militant on the anti-Soviet struggle in Afghanistan."),
("A_Feast_of_Vultures_The_Hidden_Business_of_Democracy_in_India_PDFDrive.pdf",8,"A Feast of Vultures - The Hidden Business of Democracy in India - Josy Joseph","English","Investigative journalism","Josy Joseph exposes corruption and crony networks beneath Indian democracy."),
("Aadhunik-Bharat1885-1987.pdf",8,"আধুনিক ভারত (Modern India, 1885-1947)","Bengali","History","Bengali survey history of modern India from 1885."),
("Agrojoddha -Semi-Final-pdf.pdf",13,"মাওবাদী অগ্রযোদ্ধা (Maoist Vanguard Fighters - Bangladesh)","Bengali","Biographical","Brief lives of martyred comrades of the Maoist movement in Bangladesh."),
("Ami Subhash Bolchi by Shoilesh Dey [Amarboi.com].pdf",12,"আমি সুভাষ বলছি - শৈলেশ দে (Ami Subhash Bolchi)","Bengali","Biography","Shoilesh Dey's biographical work on Subhas Chandra Bose."),
("Amiya Kumar Bagchi.pdf",9,"Reflections on the Nature of the Indian Bourgeoisie - Amiya Kumar Bagchi","English","Essay","Bagchi's 1991 essay on the character of the Indian bourgeoisie."),
("Anand Teltumbde - Republic of Caste-Navayana (2018).pdf",5,"Republic of Caste - Anand Teltumbde","English","Caste studies","Teltumbde on caste, neoliberalism and the failure of anti-caste politics in India."),
("Arundhati Book.pdf",8,"অরুন্ধতী রায়-এর পরমানন্দ ও আজকের ভারত (On Arundhati Roy and Today's India)","Bengali","Essay","Bengali cultural-magazine essay on Arundhati Roy and contemporary India."),
("B07-Selected-Readings-of-Jose-Maria-Sison.pdf",3,"Selected Readings of Jose Maria Sison","English","Political theory","Selected writings of the founder of the Communist Party of the Philippines."),
("BK-001257.pdf",12,"Baba Sohan Singh Bhakna - Founder of the Ghadar Party","English","Biography","Biography of Baba Sohan Singh Bhakna, founder of the Ghadar Party."),
("BONNEY-All-this-Burning-Earth-A5-READ.pdf",11,"All This Burning Earth - Selected Writings of Sean Bonney","English","Poetry","Selected radical poetry and writings of Sean Bonney."),
("Baba-Bujha-Singh-Biography-Ajmer-Sidhu.pdf",12,"Baba Bujha Singh - From Ghadar to Naxalbari - Ajmer Sidhu","English","Biography","Biography of revolutionary Baba Bujha Singh, from Ghadar to Naxalbari."),
("Bajol Bheri full.pdf",11,"বাজল ভেরী (Bajol Bheri)","Bengali","Literature","Bengali literary work (scanned, details not recorded)."),
("Bangla Bibhajaner Arthaniti-Rajniti.pdf",8,"বাংলা বিভাজনের অর্থনীতি-রাজনীতি (Economy and Politics of Bengal's Partition)","Bengali","History","Bengali study of the forces behind the partition of Bengal."),
("Banglay-Biplab.pdf",4,"বাংলায় বিপ্লব (Revolution in Bengal)","Bengali","History","Bengali history of revolutionary movements in Bengal."),
("Bernard_D’Mello_India_After_Naxalbari_Unfinished_History_Aakar_Books.pdf",4,"India After Naxalbari - Unfinished History - Bernard D'Mello","English","History","D'Mello's history of India's Naxalite/Maoist movement and its political context."),
("Bharater-Dwitiya_text.pdf",8,"ভারতের দ্বিতীয় স্বাধীনতার সংগ্রাম, খণ্ড ১ - ভূপেন্দ্রনাথ দত্ত","Bengali","History","Bhupendranath Dutta's political history of India's second freedom struggle, vol.1."),
("Bharatiya Krishi Aadha Samantotantrik Naki Punijibadi.pdf",9,"ভারতীয় কৃষি - আধা-সামন্ততান্ত্রিক নাকি পুঁজিবাদী? (Indian Agriculture - Semi-Feudal or Capitalist?)","Bengali","Political economy","Bengali contribution to the mode-of-production debate on Indian agriculture."),
("Bhojpur_Naxalism_In_The_Plains_of_Bihar_Kalyan_Mukherjee,_Rajendra.pdf",4,"Bhojpur - Naxalism in the Plains of Bihar - Mukherjee and Yadav","English","History","Study of the Naxalite armed peasant struggle in Bhojpur, Bihar."),
("Bhoot_Bhagaban_Saitan_Banam_Dr_Kovoor_Bhabani_Prashad_Sahoo.pdf",10,"ভূত ভগবান শয়তান বনাম ডা. কোভুর (Ghosts, God, Satan vs Dr. Kovoor)","Bengali","Rationalism","Bengali rationalist work pitting Dr. Abraham Kovoor against the supernatural."),
("BiplaberGan_ChinChingMai.pdf",11,"বিপ্লবের গান (Songs of Revolution)","Bengali","Songs","Bengali collection of revolutionary songs."),
("Black-Warrant-PDF.pdf",12,"Black Warrant - Confessions of a Tihar Jailer - Gupta and Choudhury","English","Memoir","Memoir of a Tihar Jail official on executions, inmates and prison life."),
("CAP.pdf",9,"Crisis and Predation - India, COVID-19 and Global Finance (RUPE)","English","Political economy","RUPE study of the Indian economy, COVID-19 and global finance."),
("Capital-Volume-III.pdf",1,"Capital, Volume III - Karl Marx","English","Marxist theory","Marx's third volume of Capital on capitalist production as a whole (ed. Engels)."),
("Charu Majumdar_ The Dreamer Rebel - Ashoke Mukhopadhyay.pdf",12,"Charu Majumdar - The Dreamer Rebel - Ashoke Mukhopadhyay","English","Biography","Biography of Charu Majumdar, founder-ideologue of the CPI(ML) and Naxalbari."),
("Charu_Majumder.pdf",13,"মুক্তিযুদ্ধ ও চারু মজুমদার - নেসার আহমেদ (Liberation War and Charu Majumdar)","Bengali","Essays","Nesar Ahmed (ed.), essays on the 1971 Liberation War and Charu Majumdar."),
("Corporate_Mediar_Juddho_O_Tottho_Banijjo.pdf",8,"কর্পোরেট মিডিয়ার যুদ্ধ ও তথ্য বাণিজ্য (Corporate Media's War and the Information Trade)","Bengali","Media studies","Bengali critique of corporate media, propaganda and the information business."),
("Creating a role.pdf",11,"Creating a Role - Konstantin Stanislavski","English","Theatre","Stanislavski's classic on the actor's process of building a character."),
("Dabonal_2013.pdf",16,"দাবানল ২০১৩ (Dabanal 2013)","Bengali","Magazine","Bengali little-magazine issue (2013); file encrypted, contents not extractable."),
("Debt,_the_IMF,_and_the_World_Bank_by_Eric_Toussaint_z_lib_org.pdf",9,"Debt, the IMF, and the World Bank - Eric Toussaint","English","Political economy","Primer on sovereign debt, the IMF and World Bank in the Global South."),
("DevelopmentChallengesinExtremistAffectedAreas.pdf",8,"Development Challenges in Extremist Affected Areas (Planning Commission, 2008)","English","Government report","Indian Planning Commission expert-group report on the roots of Naxalite conflict."),
("Dheu e Dheu e Talowar - Cherabandaraju.pdf",11,"ঢেউয়ে ঢেউয়ে তলোয়ার - চেরাবান্দারাজু (Dheu e Dheu e Talowar)","Bengali","Poetry","Bengali translation of revolutionary poet Cherabanda Raju's verse."),
("Drohoswar Sept. Issue (1).pdf",16,"দ্রোহস্বর - সেপ্টেম্বর সংখ্যা (Drohoswar)","Bengali","Magazine","Issue of the Bengali radical little-magazine Drohoswar."),
("EPW, Vol.60, Issue No.22, 31 May, 2025.pdf",16,"Economic and Political Weekly - Vol.60 No.22 (31 May 2025)","English","Periodical","Issue of the journal Economic and Political Weekly."),
("EconomicCrisisWarAndRevolution-NV-2004.pdf",9,"Economic Crisis, War and Revolution (New Vistas, 2004)","English","Political economy","New Vistas pamphlet linking capitalist crisis to war and revolution."),
("Einstein_and_the_philosophical_problems_of_20th_century_physics.pdf",10,"Einstein and the Philosophical Problems of 20th-Century Physics","English","Philosophy of science","Soviet-school essays on Einstein and the philosophy of modern physics."),
("Engels The Housing Question.pdf",1,"The Housing Question - Friedrich Engels","English","Marxist theory","Engels's 1872 critique of bourgeois and Proudhonist solutions to housing."),
("Fanon_Frantz_The_Wretched_of_the_Earth_1963.pdf",1,"The Wretched of the Earth - Frantz Fanon","English","Anti-colonial theory","Fanon's foundational text on decolonisation, violence and national liberation."),
("Farah_Aboubakr_The_Folktales_of_Palestine_Cultural_Identity,_Memory.pdf",7,"The Folktales of Palestine - Cultural Identity and Memory - Farah Aboubakr","English","Cultural studies","Palestinian folktales as vehicles of cultural identity and memory."),
("Fascism and social revolution.pdf",1,"Fascism and Social Revolution - R. Palme Dutt","English","Marxist theory","R. Palme Dutt's classic Marxist analysis of fascism as capitalism in decay."),
("For the solution of the ‘Caste’ question -Ranganayakamma.pdf",5,"For the Solution of the Caste Question - Ranganayakamma","English","Caste studies","Marxist examination of caste and the path to its abolition."),
("Globalization of World Politics.pdf",8,"The Globalization of World Politics - Baylis, Smith and Owens","English","International relations","Standard textbook introduction to international relations."),
("HCPSU39.pdf",1,"History of the Communist Party of the Soviet Union (Bolsheviks), 1939 - Short Course","English","History","The 1939 Short Course official history of the CPSU(B)."),
("India Waits - Jan Myrdal.pdf",8,"India Waits - Jan Myrdal","English","Reportage","Jan Myrdal's reflective travelogue and political portrait of India."),
("India's Working Class and its Prospects Part 1.pdf",9,"India's Working Class and Its Prospects, Part I (RUPE)","English","Political economy","RUPE special issue on the composition and condition of India's working class."),
("India's Working Class and its Prospects Part II.pdf",9,"India's Working Class and Its Prospects, Part II (RUPE)","English","Political economy","RUPE special issue, part II: labour under neoliberalism and organising."),
("Jangalnama-Satnam-2010-sm.pdf",4,"Jangalnama - Travels in a Maoist Guerrilla Zone - Satnam","English","Reportage","Satnam's first-hand account of life among Maoist guerrillas in Dandakaranya."),
("Jeder dewale pith diye_Koushik Banerjee .pdf",11,"যেদের দেওয়ালে পিঠ দিয়ে - কৌশিক ব্যানার্জী","Bengali","Literature","Bengali literary work by Koushik Banerjee."),
("KING, Samuel - thesis_nosignature.pdf",9,"Lenin's Theory of Imperialism Today - Samuel T. King (PhD thesis)","English","Political economy","Thesis reviving Lenin's imperialism theory to explain the global rich-poor divide."),
("Karl_Marx’s_Ecosocialism_Capital,_Nature,_and_the_Unfinished_Critique.pdf",10,"Karl Marx's Ecosocialism - Kohei Saito","English","Eco-Marxism","Saito's reconstruction of Marx's ecology and the metabolic rift."),
("Khaki and the ethnic violence in India.pdf",8,"Khaki and the Ethnic Violence in India","English","Politics","Study of the police/paramilitary role in communal and ethnic violence in India."),
("Kobad_Ghandy_Fractured_Freedom_A_Prison_Memoir_Roli_Books_2021.pdf",12,"Fractured Freedom - A Prison Memoir - Kobad Ghandy","English","Memoir","Maoist intellectual Kobad Ghandy's memoir of prison, politics and loss."),
("Kon Pothe Gelo Gaan By Kabir Sumon (bdebooks.com).pdf",11,"কোন পথে গেল গান - কবীর সুমন (Kon Pothe Gelo Gaan)","Bengali","Music and essays","Kabir Suman on the trajectory of modern Bengali song (encrypted file)."),
("Lenin-OnTheStruggleAgainstRevisionism-Peking-1960-OCR.pdf",1,"On the Struggle Against Revisionism - Lenin (Peking, 1960)","English","Marxist theory","Lenin texts on combating revisionism, issued for his 90th anniversary."),
("Lipunov_In_The_World_Of_Binary_Stars_Science_for_Everyone_Mir_1989.pdf",10,"In the World of Binary Stars - V. M. Lipunov (Science for Everyone)","English","Astronomy","Mir Science for Everyone popular astrophysics title on binary stars."),
("Livro-28-DOUGLAS-TOTTLE-–-FOME-FRAUDE-E-FASCISMO.pdf",8,"Fraud, Famine and Fascism - The Ukrainian Genocide Myth - Douglas Tottle","English","History","Tottle's contested book challenging the Holodomor genocide narrative."),
("Maa - Maxim Gorky.pdf",11,"মা - ম্যাক্সিম গোর্কি (Mother)","Bengali","Novel","Bengali translation of Maxim Gorky's revolutionary novel Mother."),
("Mahabidroh-O.pdf",8,"মহাবিদ্রোহ (The Great Rebellion of 1857)","Bengali","History","Bengali history of the 1857 revolt."),
("making_history_karnatakas_people_and_their_past_volume_2_compress.pdf",8,"Making History - Karnataka's People and Their Past, Vol. II - Saki","English","History","People's history of Karnataka, vol. II: colonial shock and armed struggle (1800-1857)."),
("Manufacturing_Consent_The_Political_Economy_of_the_Mass_Media_PDFDrive.pdf",8,"Manufacturing Consent - Herman and Chomsky","English","Media studies","Herman and Chomsky's propaganda model of the mass media."),
("Mao and People's War.pdf",3,"Mao and People's War","English","Political theory","Short work on Mao Zedong's theory of people's war."),
("Mao on Education.pdf",3,"Mao on Education","English","Political theory","Selection of Mao Zedong's writings and remarks on education."),
("MaoistEconomics-ShanghaiTextbook-Lotta-OCR-sm.pdf",3,"Maoist Economics and the Revolutionary Road to Communism - The Shanghai Textbook","English","Political economy","The Shanghai Textbook of socialist political economy, ed. Raymond Lotta."),
("Marighella-ForTheLiberationOfBrazil-1971-OCR.pdf",3,"For the Liberation of Brazil - Carlos Marighella","English","Political theory","Marighella's writings, including the Minimanual of the Urban Guerrilla."),
("Marx-Engels-Lenin-OnCommunistSociety-Moscow-1978-OCR-sm.pdf",1,"On Communist Society - Marx, Engels, Lenin (Progress, 1978)","English","Marxist theory","Progress Publishers anthology on the future communist society."),
("Marx-Grundrisse-MIA-OCR.pdf",1,"Grundrisse - Karl Marx","English","Marxist theory","Marx's 1857-61 notebooks, foundations of the critique of political economy."),
("Marxism On Vedanta.pdf",1,"Marxism on Vedanta (CPI Conference, 1975)","English","Philosophy","CPI conference papers critiquing Bani Deshpande's The Universe of Vedanta."),
("MarxistPoliticalEconomy-IntroCourse.pdf",1,"Marxist Political Economy - An Introductory Course","English","Political economy","Primer course on Marxist political economy from value to imperialism."),
("Marxs_Ecology_Materialism_and_Nature.pdf",10,"Marx's Ecology - Materialism and Nature - John Bellamy Foster","English","Eco-Marxism","Foster's recovery of the ecological materialism in Marx's thought."),
("Mastering bolshevism.pdf",1,"Mastering Bolshevism - Joseph Stalin","English","Marxist theory","Stalin's 1937 report on party cadres and vigilance."),
("May-Dibaser.pdf",99,"মে দিবসের ইতিহাস (duplicate)","Bengali","History","Duplicate of the archive.org copy of the May Day history pamphlet."),
("MLM_603.pdf",3,"Marxism-Leninism-Maoism Study Readings (MLM 603)","English","Political theory","Compilation of core Marxism-Leninism-Maoism study readings."),
("N03-Which-East-is-Red-2nd-Printing.pdf",3,"Which East Is Red? - The Maoist Presence in the USSR and Eastern Europe - Andrew Smith","English","History","FLP study of pro-Mao currents in the Soviet bloc, 1956-1980."),
("N07-Critiquing-Brahmanism.pdf",5,"Critiquing Brahmanism - K. Murali (Ajith)","English","Caste studies","Ajith's essays on Brahminism, caste and the Indian revolution (FLP)."),
("N14-The-World-Turned-Upside-Down-1st-Printing-FINAL-FINAL.pdf",4,"The World Turned Upside Down - Imperialist vs People's Development - Amit Bhattacharyya","English","Political economy","Contrasts imperialist and people's models of development (FLP)."),
("NCERT_Delhi_Historians__Group.pdf",8,"Communalisation of Education - The History Textbooks Controversy - Delhi Historians' Group","English","Education and history","Historians' rebuttal to the saffronisation of NCERT history textbooks."),
("Nandita_Haksar_Framing_Geelani,_Hanging_Afzal_Patriotism_in_the.pdf",6,"Framing Geelani, Hanging Afzal - Nandita Haksar","English","Politics and law","Haksar on the Parliament-attack case, Afzal Guru and the politics of patriotism."),
("Naxal Drohe Nari By Nesar Ahmed.pdf",14,"নকশাল দ্রোহে নারী - নেসার আহমেদ (Women in the Naxalite Revolt)","Bengali","Gender and history","Nesar Ahmed on the role of women in the Naxalite movement."),
("NaxalbariAndTheChinesePress-Anthology-2022-OCR-sm.pdf",4,"Naxalbari and the Chinese Press - A Select Anthology","English","History","Anthology of Chinese press coverage of the 1967 Naxalbari uprising."),
("Naxalbari_is_not_just_the_name_of_a_village!_25_years_of_the_Naxalite.pdf",4,"Naxalbari Is Not Just the Name of a Village! - 25 Years of the Naxalite Movement (AIRSF)","English","History","AIRSF retrospective marking 25 years of the Naxalite movement."),
("Next-to-Stalin-Notes-of-a-bodyguard-AT-Rybin-1996.pdf",12,"Next to Stalin - Notes of a Bodyguard - A. T. Rybin","English","Memoir","Reminiscences of Stalin by his long-serving bodyguard."),
("Nirbachito Kobita - Birendra Chattapadhyay (pdfpustak.com).pdf",11,"নির্বাচিত কবিতা - বীরেন্দ্র চট্টোপাধ্যায় (Selected Poems)","Bengali","Poetry","Selected poems of radical Bengali poet Birendra Chattopadhyay."),
("Nirbasiter-Atmakatha.pdf",12,"নির্বাসিতের আত্মকথা (Autobiography of an Exile)","Bengali","Memoir","Bengali prison/exile memoir from the anti-colonial revolutionary tradition."),
("On Chinese Fascism - Zhou EnLai.pdf",3,"On Chinese Fascism - Zhou Enlai","English","Political document","Zhou Enlai's text analysing fascism in China."),
("OnTheQuestionOfStalin-1963.pdf",3,"On the Question of Stalin (Peking, 1963)","English","Political document","CPC polemic replying to the CPSU's open letter."),
("OutlineHistoryOfCPI-BeforeNaxalbari.pdf",4,"Outline History of the Communist Party of India - Before Naxalbari","English","History","Survey history of the CPI up to the Naxalbari split."),
("PATRABALI - NETAJI.pdf",12,"পত্রাবলী - নেতাজী সুভাষচন্দ্র বসু (Letters of Netaji)","Bengali","Letters","Collected letters of Netaji Subhas Chandra Bose."),
("PFLP_StrategyforLiberationofPalestine1969.pdf",7,"Strategy for the Liberation of Palestine - PFLP (1969)","English","Political document","The PFLP's 1969 strategic programme for the Palestinian revolution."),
("Paani-Janatana-State.pdf",4,"Janatana State - The Maoists' Praxis in Dandakaranya - Pani","English","Reportage","Pani's account of the Maoist people's government in Dandakaranya."),
("Parallel Government in Dandakaranya by C. Vanaja (z-lib.org).pdf",4,"Parallel Government in Dandakaranya - C. Vanaja","English","Reportage","Short study of the Maoist parallel government in Dandakaranya."),
("PoliticalEconomy.pdf",1,"Political Economy - A Textbook (USSR Academy of Sciences)","English","Political economy","The classic 1954 Soviet textbook of political economy."),
("Profit_over_people_neoliberalism_and_the_global_order_PDFDrive_.pdf",9,"Profit Over People - Neoliberalism and Global Order - Noam Chomsky","English","Politics","Chomsky's critique of neoliberalism and corporate power."),
("Prostitution is a Sexual Violence.pdf",14,"Prostitution Is Sexual Violence (New Vistas)","English","Gender","New Vistas feminist pamphlet arguing prostitution is sexual violence."),
("ProstitutionIsSexualViolence-NV-2004.pdf",14,"Prostitution Is Sexual Violence (New Vistas, 2004 reprint)","English","Gender","New Vistas 2004 reprint of the pamphlet on prostitution as sexual violence."),
("RED_HAMMER_OVER_CALCUTTA_UNIVERSITY_1984_1987_SA_230502_191950_text.pdf",4,"Red Hammer over Calcutta University 1984-1987 - Santosh Bhattacharyya","English","Memoir and history","Account of leftist turmoil at Calcutta University, 1984-87."),
("Rachana-sankalan-Part.pdf",11,"রচনা সংকলন (Selected Writings)","Bengali","Anthology","Bengali selected-writings anthology (author not recorded in file)."),
("Rashid_Khalidi_The_Hundred_Years'_War_on_Palestine_A_History_of.pdf",7,"The Hundred Years' War on Palestine - Rashid Khalidi","English","History","Khalidi's history of settler colonialism and resistance in Palestine, 1917-2017."),
("RevWomensMovementIndia-NV-2004.pdf",14,"The Revolutionary Women's Movement in India (New Vistas, 2004)","English","Gender and history","New Vistas pamphlet on the revolutionary women's movement in India."),
("Revolutionary_Feminism.pdf",14,"Revolutionary Feminism - Communist Interventions, Vol. III","English","Feminist theory","Communist Research Cluster reader of revolutionary feminist texts."),
("Right to Information Act 2005.pdf",8,"The Right to Information Act, 2005","English","Law","Text of India's Right to Information Act, 2005."),
("Romila_Thapar_The_Penguin_History_of_Early_India_From_the_Origins.pdf",8,"The Penguin History of Early India - Romila Thapar","English","History","Thapar's authoritative history of India from its origins to 1300 CE."),
("Rush-Biplab.pdf",1,"রুশ বিপ্লব (The Russian Revolution)","Bengali","History","Bengali history of the 1917 Russian Revolution."),
("S10_Specific_Characteristics_of_our_People_s_War_5th_Printing.pdf",3,"Specific Characteristics of Our People's War - Jose Maria Sison","English","Political theory","Sison on applying people's war to Philippine conditions (FLP)."),
("S20-Basic-Principles-of-ML-6th-Printing.pdf",3,"Basic Principles of Marxism-Leninism - A Primer - Jose Maria Sison","English","Political theory","Sison's primer on the basic principles of Marxism-Leninism (FLP)."),
("S22-Activist-Study-ARAK-4th-Printing.pdf",3,"Activist Study (Araling Aktibista / ARAK)","English","Political education","CPP activist study course, FLP edition."),
("SBInterview22Janfinal.pdf",8,"Interview Volume (SB, January)","English","Interview","Long interview transcript volume; subject not recorded in the file metadata."),
("SGN-Bengali15.pdf",16,"সংহতি বুলেটিন ১৫ (Movement Bulletin No.15)","Bengali","Bulletin","Issue of a Bengali movement bulletin."),
("SGN-Bengali5.pdf",16,"সংহতি বুলেটিন ৫ (Movement Bulletin No.5)","Bengali","Bulletin","Issue of a Bengali movement bulletin."),
("SINGUR-APDR.pdf",4,"Singur - APDR Report","English","Report","Association for Protection of Democratic Rights report on Singur."),
("SOAS_Palestinian_Studies_Joseph_R_Farag_Politics_and_Palestinian.pdf",7,"Politics and Palestinian Literature in Exile - Joseph R. Farag","English","Literary study","Farag on exile, politics and the Palestinian short story."),
("Saki - Making History Vol 1.pdf",8,"Making History - Karnataka's People and Their Past, Vol. I - Saki","English","History","People's history of Karnataka, volume I."),
("Saroj Dutta Rachana 1.pdf",4,"সরোজ দত্ত রচনা সংকলন ১ (Collected Works of Saroj Dutta, Vol.1)","Bengali","Anthology","Writings of Naxalite poet-ideologue Saroj Dutta, vol.1."),
("Satnam_Translated_By_Vishav_Bharti_Jangalnama_Travels_in_a_Maoist.pdf",4,"Jangalnama - Travels in a Maoist Guerrilla Zone - Satnam (Bharti tr.)","English","Reportage","Vishav Bharti's English translation of Satnam's Jangalnama."),
("SelectedWorks-IbrahimKaypakkaya-2014.pdf",3,"Selected Works of Ibrahim Kaypakkaya","English","Political theory","Writings of Ibrahim Kaypakkaya, founder of the Turkish TKP/ML."),
("Sera Eksho by O. Henry.pdf",11,"সেরা একশো - ও. হেনরি (Best Hundred Stories of O. Henry)","Bengali","Short stories","Bengali translation of one hundred selected O. Henry stories."),
("Shabir Shah - The Voice of Conscience.pdf",6,"Shabir Shah - The Voice of Conscience","English","Biography","Biographical political account of Kashmiri leader Shabir Shah."),
("Soviet-Samajer-itihas.pdf",1,"সোভিয়েত সমাজের ইতিহাস (History of Soviet Society)","Bengali","History","Bengali history of Soviet society."),
("TARUNER AHOBAN - NETAJI.pdf",8,"তরুণের আহ্বান - নেতাজী সুভাষচন্দ্র বসু (The Call of Youth)","Bengali","Politics","Netaji Subhas Chandra Bose's The Call of Youth."),
("TOTTO CHAN BY TETSUKO KUYARANAGI.pdf",11,"টোট্টো-চান - তেতসুকো কুরোয়ানাগি (Totto-chan)","Bengali","Memoir","Bengali translation of Tetsuko Kuroyanagi's Totto-chan, the Little Girl at the Window."),
("Telengana biplob.pdf",4,"তেলেঙ্গানা বিপ্লব (The Telangana Armed Struggle)","Bengali","History","Bengali history of the 1946-51 Telangana peasant armed struggle."),
("The Culture of Terrorism Noam Chomsky ( PDFDrive ).pdf",8,"The Culture of Terrorism - Noam Chomsky","English","Politics","Chomsky on US foreign policy, Iran-Contra and state terror."),
("The Hanging of Afzal Guru and t - Arundhati Roy.pdf",6,"The Hanging of Afzal Guru and the Attack on the Indian Parliament - Arundhati Roy (ed.)","English","Politics and law","Essays questioning the trial and execution of Afzal Guru."),
("The Huey P. Newton Reader.pdf",8,"The Huey P. Newton Reader","English","Politics","Selected writings and speeches of Black Panther co-founder Huey P. Newton."),
("The Indian Big Bourgeoisie.pdf",9,"The Indian Big Bourgeoisie","English","Political economy","Study of the structure and power of India's big bourgeoisie."),
("The Political Writings of Bhagat Singh.pdf",8,"The Political Writings of Bhagat Singh - ed. Chaman Lal","English","Politics","Bhagat Singh's essays and prison writings."),
("The Soccer in Sun and Shadow by Eduardo Galeano (z-lib.org).pdf",11,"Soccer in Sun and Shadow - Eduardo Galeano","English","Sport and essays","Galeano's lyrical history of football, its beauty and its politics."),
("The-life-and-work-of-Dr.-R.H.-Richharia.pdf",10,"The Life and Work of Dr. R. H. Richharia - Bharat Dogra","English","Biography and science","On the rice scientist who defended Indian farmers' seed heritage."),
("TheHistoryOfAlbania-ABriefSurvey-1964-OCR-sm.pdf",8,"The History of Albania - A Brief Survey - Kristo Frasheri","English","History","Concise survey history of Albania (Tirana, 1964)."),
("TheScalpelAndTheSword-BethuneBiography-1952.pdf",12,"The Scalpel, the Sword - The Story of Doctor Norman Bethune - Allan and Gordon","English","Biography","Biography of Dr. Norman Bethune, surgeon and internationalist."),
("TheScienceOfRevolution-Wolff.pdf",3,"The Science of Revolution - Lenny Wolff","English","Political theory","Wolff's exposition of revolutionary communist theory (RCP-USA)."),
("The_Italian_Resistance_Fascists_Guerrillas_and_the_Allies.pdf",8,"The Italian Resistance - Fascists, Guerrillas and the Allies - Tom Behan","English","History","Tom Behan's history of the Italian partisan resistance."),
("The_Lie_of_Global_Prosperity_How_Neoliberals_Distort_Data_to_Mask.pdf",9,"The Lie of Global Prosperity - Seth Donnelly","English","Political economy","Donnelly debunks rosy neoliberal poverty statistics."),
("The_tragic_partition_of_Bengal_Suniti_Kumar_Ghosh_1_ed_,_2002_Indian.pdf",8,"The Tragic Partition of Bengal - Suniti Kumar Ghosh","English","History","Suniti Kumar Ghosh on the politics of Bengal's partition."),
("TwelfthSessionOfCCofSED-1969-Doc1.pdf",16,"Twelfth Session of the CC of the SED (Berlin, 1969)","English","Party document","Proceedings of the Socialist Unity Party of Germany CC, Dec 1969."),
("Vietnam o Kolkata.pdf",4,"ভিয়েতনাম ও কলকাতা (Vietnam and Calcutta)","Bengali","History","Bengali account linking Vietnam solidarity and Calcutta's radical 1960s-70s."),
("Volga Theke Ganga .pdf",11,"ভলগা থেকে গঙ্গা - রাহুল সাংকৃত্যায়ন (From Volga to Ganga)","Bengali","Historical fiction","Bengali translation of Rahul Sankrityayan's sweeping historical story-cycle."),
("WomenInChineseRevolution-NV-2004.pdf",14,"Women in the Chinese Revolution 1921-50 (New Vistas)","English","Gender and history","New Vistas pamphlet on women in the Chinese revolution and socialist China."),
("Women_in_Peasant_Movements_Tebhaga,_Naxalite_and_After_Debal_K_Singha.pdf",14,"Women in Peasant Movements - Tebhaga, Naxalite and After - Debal K. Singha Roy","English","Gender and history","Women's participation in the Tebhaga and Naxalite peasant movements."),
("[Vaclav_Smil]_Energy_and_Civilization_A_History).pdf",10,"Energy and Civilization - A History - Vaclav Smil","English","History of science","Smil's panoramic history of energy use across human civilisation."),
("a-mirror.pdf",3,"A Mirror for Revisionists (CPC, 1963)","English","Political document","Chinese Communist Party polemic against Soviet revisionism."),
("ajitha-keralas-naxalbari_compress.pdf",12,"Kerala's Naxalbari - Ajitha: Memoirs of a Young Revolutionary","English","Memoir","Ajitha's memoir of the Naxalite movement in Kerala."),
("aspects-75-76.pdf",9,"Aspects of India's Economy, Nos. 75 and 76 (RUPE)","English","Political economy","RUPE journal issue on the farm laws and India's agrarian economy."),
("che_guevara_on_socialism_and_internationalism.pdf",1,"Che Guevara on Socialism and Internationalism","English","Politics","Collection of Che Guevara's writings on socialism and internationalism."),
("chico_mendes_fight_for_the_forest_chico_mendes_in_his_own_words.pdf",10,"Fight for the Forest - Chico Mendes in His Own Words","English","Ecology","Brazilian rubber-tapper unionist Chico Mendes on defending the Amazon."),
("chinapiece1.pdf",3,"চীন বিপ্লব প্রসঙ্গে (On the Chinese Revolution - essay)","Bengali","Essay","Bengali essay on the Chinese revolution."),
("condition-working-class-england.pdf",1,"The Condition of the Working Class in England - Friedrich Engels","English","Marxist theory","Engels's 1845 investigation of industrial working-class life in England."),
("convrsion of parliamentarism to social fascism.pdf",4,"Conversion of Parliamentarism to Social Fascism - An Indian Experience - Siraj","English","Politics","Critique of the CPI(M)'s parliamentary road in West Bengal."),
("deshopremi jan 21.pdf",16,"দেশপ্রেমী - জানুয়ারি ২০২১ (Deshopremi, Jan 2021)","Bengali","Magazine","Issue of the Bengali magazine Deshopremi."),
("development-dignity-bhaduri.pdf",9,"Development with Dignity - Amit Bhaduri","English","Political economy","Bhaduri's argument for full-employment, people-centred development."),
("fdocuments.in_samir-amin-the-liberal-virus.pdf",9,"The Liberal Virus - Samir Amin","English","Political economy","Samir Amin's critique of liberal ideology and US-led globalisation."),
("gujrat-files.pdf",8,"Gujarat Files - Anatomy of a Cover Up - Rana Ayyub","English","Investigative journalism","Rana Ayyub's sting investigation into the 2002 Gujarat violence."),
("itibritte chandal jibon.pdf",5,"ইতিবৃত্তে চণ্ডাল জীবন - মনোরঞ্জন ব্যাপারী (Interrogating My Chandal Life)","Bengali","Memoir","Manoranjan Byapari's celebrated Dalit autobiography."),
("jatisomyai marxbad.pdf",5,"জাতিসাম্যে মার্কসবাদ (Marxism on Caste Equality)","Bengali","Caste and theory","Bengali Marxist treatment of caste and the struggle for equality."),
("lenin-samajtantrik-biplab.pdf",1,"লেনিন - সমাজতান্ত্রিক বিপ্লব (Lenin on Socialist Revolution)","Bengali","Marxist theory","Bengali collection of Lenin on the socialist revolution."),
("murray-bookchin-the-ecology-of-freedom.lt.pdf",10,"The Ecology of Freedom - Murray Bookchin","English","Social ecology","Bookchin's work on hierarchy, domination and an ecological society."),
("navlakha_days_and_nights1.pdf",4,"Days and Nights in the Heartland of Rebellion - Gautam Navlakha","English","Reportage","Navlakha's first-hand account of travelling with Maoist guerrillas."),
("nazariya-magazine-land-struggle-in-india-1.pdf",16,"Nazariya Magazine - Land Struggles in India (Issue 2)","English","Magazine","Nazariya issue on land struggles, green revolution and agrarian relations."),
("notesonindianhistory-marx.pdf",8,"Notes on Indian History (664-1858) - Karl Marx","English","History","Marx's chronological notes on Indian history."),
("null-1.pdf",16,"সহযোদ্ধা সংখ্যা ৫ (Sahojoddha No.5)","Bengali","Magazine","Cultural organ of the Purba Banglar Sarbahara Party, issue 5."),
("null-7.pdf",6,"কাশ্মীরের কৃষক ও শ্রমিক আন্দোলন (Kashmir - Peasant and Worker Movements)","Bengali","History","Bengali short history of Kashmir and its peasant-worker movements."),
("null-8.pdf",5,"The Persistence of Caste - The Khairlanji Murders and India's Hidden Apartheid - Anand Teltumbde","English","Caste studies","Teltumbde's anatomy of the Khairlanji massacre and caste atrocity."),
("prosnottore_jati_borno_byabostha_o_songrokkhon_byabostha_merged.pdf",5,"প্রশ্নোত্তরে জাতি-বর্ণ ব্যবস্থা ও সংরক্ষণ (Caste and Reservation, in Q&A)","Bengali","Caste studies","Bengali question-and-answer primer on caste and reservations."),
("scienceinsaffron.pdf",10,"Science in Saffron - Skeptical Essays on History of Science - Meera Nanda","English","History of science","Meera Nanda debunks claims of ancient Hindu scientific achievement."),
("spring_thunder.pdf",4,"Spring Thunder - Naxalbari and After","English","History","Account of the Naxalbari Spring Thunder uprising and its aftermath."),
("storming the gates of heaven.pdf",1,"Storming the Gates of Heaven","English","History","Large radical-history volume; specific subject not recorded in file metadata."),
("sukanto_somogra.pdf.pdf",11,"সুকান্ত সমগ্র (Complete Works of Sukanta Bhattacharya)","Bengali","Poetry","Collected works of revolutionary Bengali poet Sukanta Bhattacharya."),
("the many faces of kashmiri nationalism.pdf",6,"The Many Faces of Kashmiri Nationalism - Nandita Haksar","English","History","Kashmiri nationalism through the lives of Sampat Prakash and Afzal Guru."),
("three-writings.pdf",4,"Three Writings (Naxalite movement)","English","Political document","Pamphlet collecting three revolutionary writings."),
("trade-union-lenin.pdf",1,"Lenin on Trade Unions","English","Marxist theory","Anthology of Lenin's writings on trade unions."),
("various-authors-class-struggle-and-mental-health.pdf",10,"Class Struggle and Mental Health - Live to Fight Another Day (libcom.org)","English","Essays","Anthology connecting mental health, capitalism and activist self-care."),
("what-happened-at-the-park.pdf",16,"What Happened at the Park","English","Pamphlet","Short illustrated political pamphlet."),
("zuge_zuge_maolana_vashanir_songgram.pdf",13,"যুগে যুগে মওলানা ভাসানীর সংগ্রাম - শাহ আহমদ রেজা","Bengali","Biography","Shah Ahmed Reza on the political struggles of Maulana Bhashani."),
("অপ্রকাশিত_রাজনৈতিক_ইতিহাস_ভূপেন্দ্রনাথ_দত্ত.pdf",8,"অপ্রকাশিত রাজনৈতিক ইতিহাস - ভূপেন্দ্রনাথ দত্ত (Unpublished Political History)","Bengali","History","Bhupendranath Dutta's unpublished political history of India's freedom struggle."),
("অর্থনীতিবাদ_প্রসঙ্গে_লেনিন.pdf",1,"অর্থনীতিবাদ প্রসঙ্গে - লেনিন (Lenin on Economism)","Bengali","Marxist theory","Lenin on economism, in Bengali."),
("অ্যানিম্যাল_ফার্ম_Boiersomahar.pdf",11,"অ্যানিম্যাল ফার্ম - জর্জ অরওয়েল (Animal Farm)","Bengali","Novel","Bengali translation of George Orwell's Animal Farm."),
("আখতারুজ্জামান_ইলিয়াস_রচনাসমগ্ৰ1.pdf",11,"আখতারুজ্জামান ইলিয়াস রচনাসমগ্র ১ (Collected Works of Akhtaruzzaman Elias, Vol.1)","Bengali","Fiction","Collected works of the major Bangladeshi novelist Akhtaruzzaman Elias, vol.1."),
("আজকের এ ভারত.pdf",8,"আজকের এ ভারত (India Today)","Bengali","Politics","Bengali political commentary on contemporary India."),
("আজাদ একটি হত্যা.pdf",4,"আজাদ - একটি হত্যা (Azad - A Killing)","Bengali","Politics","Bengali account of the killing of Maoist leader Cherukuri Rajkumar Azad."),
("আপনাকে_বলছি_স্যার_সলিল_বিশ্বাস.pdf",8,"আপনাকে বলছি স্যার - সলিল বিশ্বাস","Bengali","Essays","Salil Biswas's Bengali essays addressed to authority."),
("আমার_কারাজীবনী_উল্লাসকর_দত্ত.pdf",12,"আমার কারাজীবনী - উল্লাসকর দত্ত (My Prison Life)","Bengali","Memoir","Revolutionary Ullaskar Dutta's memoir of imprisonment in the Andamans."),
("উত্তরকালের_গল্পসংগ্রহ_মানিক_বন্দ্যোপাধ্যায়.pdf",11,"উত্তরকালের গল্পসংগ্রহ - মানিক বন্দ্যোপাধ্যায় (Later Stories)","Bengali","Short stories","Later short stories of Manik Bandyopadhyay."),
("ঐতিহাসিক চীন বিপ্লব.pdf",3,"ঐতিহাসিক চীন বিপ্লব (The Historic Chinese Revolution)","Bengali","History","Bengali account of the Chinese revolution."),
("কম_সুশীল_রায়ের_চিঠি_বুদ্ধদেব_ভট্টাচার্যকে.pdf",4,"কমরেড সুশীল রায়ের চিঠি বুদ্ধদেব ভট্টাচার্যকে","Bengali","Politics","Open letter from imprisoned Maoist leader Sushil Roy to the West Bengal CM."),
("কমিউনিস্ট_পার্টির_সংগঠন.pdf",1,"কমিউনিস্ট পার্টির সংগঠন (Organisation of the Communist Party)","Bengali","Politics","Bengali manual on communist party organisation."),
("কমিউনিস্ট_ম্যানিফেস্টো_সংগ্রামের_দিশা.pdf",1,"কমিউনিস্ট ম্যানিফেস্টো ও সংগ্রামের দিশা (The Communist Manifesto)","Bengali","Marxist theory","Bengali edition of the Communist Manifesto with commentary."),
("কম‌রেড_অনু_স্মারকগ্রন্থ_Comrade_Anuradha_Shanbag_Ghandy.pdf",12,"কমরেড অনু - অনুরাধা গান্ধী স্মারকগ্রন্থ (Comrade Anuradha Ghandy Memorial Volume)","Bengali","Biography","Memorial volume for Maoist leader Anuradha Ghandy."),
("কাকে বলে ইতিহাস.pdf",8,"কাকে বলে ইতিহাস (What Is History?)","Bengali","History and theory","Bengali treatment of the philosophy of history."),
("কালাপানির_হাতছানি_বিলেতে_বাঙালির_ইতিহাস.pdf",8,"কালাপানির হাতছানি - বিলেতে বাঙালির ইতিহাস (History of Bengalis in Britain)","Bengali","History","Bengali history of Bengali migrants and travellers in Britain."),
("কাশ্মীর।_সিদ্ধার্থ_গুহ.pdf",6,"কাশ্মীর - সিদ্ধার্থ গুহ (Kashmir)","Bengali","Politics and history","Siddhartha Guha's Bengali book on Kashmir."),
("চতুর্থ শিল্প বিপ্লব.pdf",16,"চতুর্থ শিল্প বিপ্লব ও ছাত্র আন্দোলন (The Fourth Industrial Revolution and the Student Movement)","Bengali","Pamphlet","Bengali pamphlet on the fourth industrial revolution and student politics."),
("জনতন_রাজ্য_দন্ডকারণ্যে_মাওবাদীদের_অনুশীলন.pdf",4,"জনতন রাজ্য - দন্ডকারণ্যে মাওবাদীদের অনুশীলন (Janatana Sarkar - Bengali)","Bengali","Reportage","Bengali edition of Pani's account of the Maoist people's government in Dandakaranya."),
("দ্বেষ_বীরেন্দ্র_চট্টোপাধ্যায়_.pdf",11,"দ্বেষ - বীরেন্দ্র চট্টোপাধ্যায় (Dwesh)","Bengali","Poetry","Poem by Birendra Chattopadhyay."),
("দ্রোহজ.pdf",16,"দ্রোহজ (Drohoj)","Bengali","Magazine","Issue of a Bengali radical little-magazine."),
("ধর্ম প্রসঙ্গে- লেনিন.pdf",1,"ধর্ম প্রসঙ্গে - লেনিন (Lenin on Religion)","Bengali","Marxist theory","Lenin's writings on religion, in Bengali."),
("নমশূদ্রের_ইতিহাস_বিপুল_কুমার_রায়.pdf",5,"নমশূদ্রের ইতিহাস - বিপুল কুমার রায় (History of the Namasudras)","Bengali","Caste and history","History of the Namasudra Dalit community of Bengal."),
("না বলতে শিখুন .pdf",11,"না বলতে শিখুন (Learn to Say No)","Bengali","Self-help","Bengali self-help book on assertiveness."),
("নয়াগণতন্ত্র প্রসঙ্গে.pdf",3,"নয়াগণতন্ত্র প্রসঙ্গে - মাও সেতুং (On New Democracy)","Bengali","Political theory","Mao's On New Democracy, in Bengali."),
("পঞ্চাশের_মন্বন্তের_চার্চিলের_ষড়যন্ত্র_মধুশ্রী_মুখোপাধ্যায়_eboi_org.pdf",8,"পঞ্চাশের মন্বন্তর ও চার্চিলের ষড়যন্ত্র - মধুশ্রী মুখোপাধ্যায় (Churchill's Secret War)","Bengali","History","Bengali edition of Madhusree Mukerjee on Churchill and the 1943 Bengal famine."),
("পাগলা_কুত্তা_ও_অন্যান্য_গল্প.pdf",11,"পাগলা কুত্তা ও অন্যান্য গল্প (The Mad Dog and Other Stories)","Bengali","Short stories","Bengali short-story collection."),
("পায়ে_পায়ে_কমরেড_দের_সঙ্গে.pdf",4,"পায়ে পায়ে কমরেডদের সঙ্গে (Step by Step with the Comrades)","Bengali","Reportage","Bengali memoir of time spent with revolutionary comrades."),
("পুরাকাল_ও_পক্ষপাত_রোমিলা_থাপর_amarboi_com.pdf",8,"পুরাকাল ও পক্ষপাত - রোমিলা থাপর (The Past and Prejudice)","Bengali","History","Bengali translation of Romila Thapar's The Past and Prejudice."),
("পূর্ব_বাঙলার_ভাষা_আন্দোলন_ও_তৎকালীন_রাজনীতি_০১_বদরুদ্দীন_উমর.pdf",13,"পূর্ব বাঙলার ভাষা আন্দোলন ও তৎকালীন রাজনীতি ১ - বদরুদ্দীন উমর","Bengali","History","Badruddin Umar's classic history of the 1952 Bengali Language Movement, vol.1."),
("প্যালেস্টাইনের_গল্প,_কবিতা_প্রবন্ধ.pdf",7,"প্যালেস্টাইনের গল্প, কবিতা, প্রবন্ধ (Palestinian Stories, Poems and Essays)","Bengali","Anthology","Bengali anthology of Palestinian fiction, poetry and essays."),
("প্রকৃতির_দ্বান্দ্বিকতা_ফ্রেডারিক_এঙ্গেলস.pdf",1,"প্রকৃতির দ্বান্দ্বিকতা - ফ্রেডরিক এঙ্গেলস (Dialectics of Nature)","Bengali","Marxist theory","Bengali translation of Engels's Dialectics of Nature."),
("প্রাচীন_ভারতে_গণিকা_সুকুমারী_ভট্টাচার্য.pdf",8,"প্রাচীন ভারতে গণিকা - সুকুমারী ভট্টাচার্য (Courtesans in Ancient India)","Bengali","History","Sukumari Bhattacharji on courtesans in ancient India."),
("প্রোটোকলস_অব_জায়োনিজম.pdf",7,"প্রোটোকলস অব জায়োনিজম (On Zionism)","Bengali","Politics","Bengali book critically examining Zionism and its politics."),
("ফাঁসির_মঞ্চ_থেকে,_জুলিয়াস_ফুচিক.pdf",12,"ফাঁসির মঞ্চ থেকে - জুলিয়াস ফুচিক (Notes from the Gallows)","Bengali","Memoir","Bengali translation of Julius Fucik's anti-Nazi prison testament."),
("ফ্যাসিজমের_বিরুদ্ধে_ম্যাক্সিম_গোর্কি.pdf",1,"ফ্যাসিজমের বিরুদ্ধে - ম্যাক্সিম গোর্কি (Against Fascism)","Bengali","Essays","Maxim Gorky's anti-fascist writings, in Bengali."),
("বনি_ইসরায়েল_থেকে_আজকের_ইহুদি.pdf",7,"বনি ইসরায়েল থেকে আজকের ইহুদি (From the Children of Israel to Today's Jews)","Bengali","History","Bengali history of the Jewish people from antiquity to the present."),
("বাল্মীকির_রাম_ফিরে_দেখা.pdf",8,"বাল্মীকির রাম - ফিরে দেখা (Valmiki's Rama Revisited)","Bengali","Literature and history","Bengali critical re-reading of Rama in Valmiki's Ramayana."),
("বিএনপির_অপকর্মের_খতিয়ান.pdf",13,"জুলাই বিপ্লবের ৫০০ দিন - বিএনপির অপকর্মের খতিয়ান","Bengali","Politics","Bangladeshi political tract cataloguing the BNP's record."),
("বিদ্যাসাগর_নানা_প্রসঙ্গ_রামকৃষ্ণ_ভট্টাচার্য.pdf",8,"বিদ্যাসাগর - নানা প্রসঙ্গ - রামকৃষ্ণ ভট্টাচার্য","Bengali","Biography and essays","Ramkrishna Bhattacharya's essays on Ishwar Chandra Vidyasagar."),
("ভগৎ সিং .pdf",12,"ভগৎ সিং (Bhagat Singh)","Bengali","Biography","Bengali biography and writings of Bhagat Singh."),
("ভারতীয়_অর্থনীতি_কোবাদ_ঘান্দী.pdf",9,"ভারতীয় অর্থনীতি - কোবাদ ঘান্দী (The Indian Economy)","Bengali","Political economy","Kobad Ghandy's Bengali essay on the Indian economy."),
("ভারতের_আধা_সামন্ততন্ত্র_ও_সাম্রাজ্যবাদী_লুন্ঠন.pdf",9,"ভারতের আধা-সামন্ততন্ত্র ও সাম্রাজ্যবাদী লুণ্ঠন","Bengali","Political economy","Bengali analysis of semi-feudalism and imperialist exploitation in India."),
("ভারতের_কৃষক_বিদ্রোহ_ও_গণতান্ত্রিক_সংগ্রাম.pdf",8,"ভারতের কৃষক-বিদ্রোহ ও গণতান্ত্রিক সংগ্রাম - সুপ্রকাশ রায়","Bengali","History","Suprakash Ray's classic Bengali history of Indian peasant revolts."),
("ভারতের_শ্রমিক_আন্দোলনের_ইতিহাস_গোপাল_ঘোষ.pdf",8,"ভারতের শ্রমিক আন্দোলনের ইতিহাস - গোপাল ঘোষ","Bengali","History","Gopal Ghosh's Bengali history of the Indian labour movement."),
("ভারতের_শ্রমিক_আন্দোলনের_ইতিহাস_সুকোমল_সেন.pdf",8,"ভারতের শ্রমিক আন্দোলনের ইতিহাস - সুকোমল সেন","Bengali","History","Sukomal Sen's Bengali history of the Indian working-class movement."),
("ভাষা_দক্ষিণ_চব্বিশ_পরগণা_ও_বিবিধ_নিবন্ধ.pdf",8,"ভাষা, দক্ষিণ চব্বিশ পরগণা ও বিবিধ নিবন্ধ","Bengali","Essays","Bengali essays on dialect, the South 24 Parganas region and allied themes."),
("ভেদ_বিভেদ_দাঙ্গা,_দেশভাগ_ও_সাম্প্রদায়িকতাবিরোধী_সর্বভারতীয়_গল্প.pdf",11,"ভেদ-বিভেদ, দাঙ্গা, দেশভাগ ও সাম্প্রদায়িকতাবিরোধী সর্বভারতীয় গল্প","Bengali","Short stories","All-India anthology of anti-communal stories on partition and riots."),
("মওলানা ভাসানীর রচনা.pdf",13,"মওলানা ভাসানীর রচনা (Writings of Maulana Bhashani)","Bengali","Politics","Collected writings of Maulana Abdul Hamid Khan Bhashani."),
("মাও রেডবুক.pdf",3,"মাও রেডবুক (Quotations from Chairman Mao - Little Red Book)","Bengali","Political theory","Bengali edition of Quotations from Chairman Mao Zedong."),
("মাও_অনুশীলন_ও_দ্বন্দ্ব_.pdf",3,"মাও - অনুশীলন ও দ্বন্দ্ব (Mao - On Practice and Contradiction)","Bengali","Political theory","Bengali edition of Mao's On Practice and On Contradiction."),
("মানিক_বন্দ্যোপাধ্যায়ের_শ্রেষ্ঠ_উপন্যাস.pdf",11,"মানিক বন্দ্যোপাধ্যায়ের শ্রেষ্ঠ উপন্যাস (Best Novels of Manik Bandyopadhyay)","Bengali","Novels","Selected novels of Manik Bandyopadhyay."),
("মার্ক্স_এঙ্গেলস_রচনা_সংকলণ_১.pdf",1,"মার্ক্স-এঙ্গেলস রচনা সংকলন ১ (Marx-Engels Selected Works, Vol.1)","Bengali","Marxist theory","Bengali selected works of Marx and Engels, vol.1."),
("মার্ক্স_এঙ্গেলস_রচনা_সংকলন_২.pdf",1,"মার্ক্স-এঙ্গেলস রচনা সংকলন ২ (Marx-Engels Selected Works, Vol.2)","Bengali","Marxist theory","Bengali selected works of Marx and Engels, vol.2."),
("মার্ক্সের_ক্যাপিটাল_সুপ্রকাশ_রায়.pdf",1,"মার্ক্সের ক্যাপিটাল - সুপ্রকাশ রায় (Marx's Capital, explained)","Bengali","Marxist theory","Suprakash Ray's Bengali exposition of Marx's Capital."),
("মাস লাইন অমূল্য সেন.pdf",1,"মাস লাইন - অমূল্য সেন (The Mass Line)","Bengali","Politics","Amulya Sen's Bengali essay on the communist mass line."),
("রক্তে_লেখা_ইতিহাস_কাশীপুর_বরানগর_হত্যাকান্ড.pdf",4,"রক্তে লেখা ইতিহাস - কাশীপুর-বরানগর হত্যাকাণ্ড","Bengali","History","Bengali account of the 1971 Cossipore-Baranagar massacre of Naxalites."),
("রুনু-সাদা-না-রুনু-কালো.pdf",11,"রুনু সাদা না রুনু কালো (Runu - White or Black)","Bengali","Fiction","Bengali short fiction."),
("লাল তমসুক.pdf",11,"লাল তমসুক (Lal Tomsuk)","Bengali","Novel","Bengali novel."),
("শিল্পীর_নবজন্ম_খণ্ড১.pdf",11,"শিল্পীর নবজন্ম, খণ্ড ১ - স্তানিস্লাভস্কি (An Actor's Rebirth, Vol.1)","Bengali","Theatre","Bengali translation of Stanislavski's work on acting, vol.1."),
("শিল্পীর_নবজন্ম_খণ্ড২.pdf",11,"শিল্পীর নবজন্ম, খণ্ড ২ - স্তানিস্লাভস্কি (An Actor's Rebirth, Vol.2)","Bengali","Theatre","Bengali translation of Stanislavski's work on acting, vol.2."),
("শ্রেষ্ঠ_উর্দুগল্প_১ম_খণ্ড.pdf",11,"শ্রেষ্ঠ উর্দু গল্প, ১ম খণ্ড (Best Urdu Stories, Vol.1)","Bengali","Short stories","Bengali translations of the best Urdu short stories, vol.1."),
("সন্ত্রাসবাদীর প্রতি.pdf",8,"সন্ত্রাসবাদীর প্রতি (To the Terrorist)","Bengali","Politics","Bengali political tract addressed to the revolutionary terrorist tradition."),
("সাঁওতাল_গণসংগ্রামের_ইতিহাস.pdf",8,"সাঁওতাল গণসংগ্রামের ইতিহাস (History of the Santhal People's Struggle)","Bengali","History","Bengali history of the Santhal rebellion and adivasi struggles."),
("সাম্প্রদায়িক_রাজনীতি_ও_সংঘ_পরিবার.pdf",8,"সাম্প্রদায়িক রাজনীতি ও সংঘ পরিবার - সব্যসাচী গোস্বামী","Bengali","Politics","Sabyasachi Goswami on communal politics and the RSS/Sangh Parivar."),
("সাম্রাজ্যবাদ_পুঁজিবাদের_সর্বোচ্চ_পর্যায়.pdf",1,"সাম্রাজ্যবাদ - পুঁজিবাদের সর্বোচ্চ পর্যায় - লেনিন (Imperialism)","Bengali","Marxist theory","Bengali edition of Lenin's Imperialism, the Highest Stage of Capitalism."),
("সি এম এর রাজনীতি.pdf",4,"সি এম-এর রাজনীতি (The Politics of Charu Majumdar)","Bengali","Politics","Bengali essay on the politics of Charu Majumdar."),
("সিরাজ_সিকদার_রচনা_পূর্ববাংলার_সামাজিক_বিকাশের_বর্তমান_পর্যায়ে.pdf",13,"সিরাজ সিকদার রচনা - পূর্ববাংলার সামাজিক বিকাশের বর্তমান পর্যায়ে","Bengali","Political writing","Siraj Sikder on the current stage of East Bengal's social development."),
("সুবিমল_মিশ্র_অ্যান্টি_গল্পসংগ্রহ_১.pdf",11,"সুবিমল মিশ্র অ্যান্টি-গল্পসংগ্রহ ১ (Subimal Misra Anti-Stories, Vol.1)","Bengali","Short stories","Experimental anti-establishment stories of Subimal Misra, vol.1."),
("সুবিমলমিশ্র_অ্যান্টি_গল্পসংগ্রহ_৩.pdf",11,"সুবিমল মিশ্র অ্যান্টি-গল্পসংগ্রহ ৩ (Subimal Misra Anti-Stories, Vol.3)","Bengali","Short stories","Experimental anti-establishment stories of Subimal Misra, vol.3."),
("সুবিমলমিশ্র_অ্যান্টি_গল্পসংগ্রহ_৪.pdf",11,"সুবিমল মিশ্র অ্যান্টি-গল্পসংগ্রহ ৪ (Subimal Misra Anti-Stories, Vol.4)","Bengali","Short stories","Experimental anti-establishment stories of Subimal Misra, vol.4."),
("সুভাষ_মুখোপাধ্যায়_কবিতা_এই_ভাই.pdf",11,"এই ভাই - সুভাষ মুখোপাধ্যায় (Poems)","Bengali","Poetry","Poems of Subhash Mukhopadhyay."),
("সেন্দ্রা.pdf",4,"সেন্দ্রা - কে শিকার, কে শিকারি (Sendra)","Bengali","Reportage","Bengali account of the adivasi Sendra hunt festival and who is hunter or hunted."),
("সোভিয়েত_অর্থনীতির_সমালোচনা_মাও_সেতুঙ.pdf",3,"সোভিয়েত অর্থনীতির সমালোচনা - মাও সেতুং (A Critique of Soviet Economics)","Bengali","Political economy","Bengali edition of Mao's critique of Soviet economics."),
("স্পাই স্টোরিজ ২.pdf",11,"স্পাই স্টোরিজ ২ (Spy Stories, Vol.2)","Bengali","Fiction","Bengali spy-story collection (encrypted file)."),
("স্বাধীনতা_সংগ্রামে_বাংলার_ছাত্র_সমাজ_গৌতম_চট্টোপাধ্যায়.pdf",8,"স্বাধীনতা সংগ্রামে বাংলার ছাত্রসমাজ - গৌতম চট্টোপাধ্যায়","Bengali","History","Gautam Chattopadhyay on Bengal's students in the freedom struggle."),
("স্বাধীনতার_খোঁজে_কোবাদ_ঘান্দী.pdf",12,"স্বাধীনতার খোঁজে - কোবাদ ঘান্দী (In Search of Freedom)","Bengali","Memoir","Kobad Ghandy's reflections in Bengali, companion to Fractured Freedom."),
("১৮৫৭_স্বাধীনতা_যুদ্ধের_উপাখ্যান.pdf",8,"১৮৫৭ স্বাধীনতা যুদ্ধের উপাখ্যান (The Saga of the 1857 War of Independence)","Bengali","History","Bengali narrative of the 1857 revolt (encrypted file)."),
("‘ভালো_মানুষে’র_গল্প_এবং_অরবিন্দ_কেজরিওয়াল_1.pdf",8,"ভালো মানুষের গল্প এবং অরবিন্দ কেজরিওয়াল","Bengali","Politics","Bengali political critique of Arvind Kejriwal and the AAP."),
# ---- Cybersecurity subfolder ----
("Cybersecurity/Android Hacker's Handbook.pdf",15,"Android Hacker's Handbook - Drake et al.","English","Cybersecurity","Comprehensive reference on Android internals and exploitation."),
("Cybersecurity/Android_Security_Internals_An_In_Depth_Guide_to_Android_s_Security.pdf",15,"Android Security Internals - Nikolay Elenkov","English","Cybersecurity","In-depth guide to Android's security architecture."),
("Cybersecurity/Black Hat GraphQL - Attacking Next Generation APIs.pdf",15,"Black Hat GraphQL - Attacking Next-Generation APIs - Aleks and Farhi","English","Cybersecurity","Offensive and defensive testing of GraphQL APIs."),
("Cybersecurity/BlackHat GraphQL.pdf",99,"Black Hat GraphQL (duplicate copy)","English","Cybersecurity","Second copy of Black Hat GraphQL (different scan)."),
("Cybersecurity/dokumen.pub_hacking-apis-breaking-web-application-programming-interface-9781718502444-9781718502451-2021061101-2021061102.pdf",15,"Hacking APIs - Breaking Web Application Programming Interfaces - Corey J. Ball","English","Cybersecurity","Practical guide to discovering and exploiting API vulnerabilities."),
("Cybersecurity/Hardware_Hacking_Handbook_Early_Release_1593278748.pdf",15,"The Hardware Hacking Handbook - van Woudenberg and O'Flynn","English","Cybersecurity","Breaking embedded hardware - fault injection and side-channel attacks."),
("Cybersecurity/Penetration Testing - A hands-on introduction to Hacking.pdf",15,"Penetration Testing - A Hands-On Introduction to Hacking - Georgia Weidman","English","Cybersecurity","Hands-on introduction to penetration testing."),
("Cybersecurity/The Anarchist Cookbook ( PDFDrive ) (1).pdf",15,"The Anarchist Cookbook - William Powell","English","Miscellany","The notorious 1971 underground manual (of historical interest only)."),
("Cybersecurity/The Android Malware Handbook @redbluehit (2023).pdf",15,"The Android Malware Handbook - Han et al.","English","Cybersecurity","Detecting and analysing Android malware with machine learning."),
("Cybersecurity/_OceanofPDF.com_From_Day_Zero_to_Zero_Day_-_Eugene_Lim.pdf",15,"From Day Zero to Zero Day - Eugene Lim","English","Cybersecurity","Guide to finding zero-day vulnerabilities."),
# ---- Political subfolders ----
("Political/MAO/Agrojoddha -Semi-Final-pdf.pdf",99,"মাওবাদী অগ্রযোদ্ধা (duplicate)","Bengali","Biographical","Duplicate copy of Maoist Vanguard Fighters."),
("Political/MAO/Mao and People's War.pdf",99,"Mao and People's War (duplicate)","English","Political theory","Duplicate copy."),
("Political/MAO/Mao on Education.pdf",99,"Mao on Education (duplicate)","English","Political theory","Duplicate copy."),
("Political/MAO/MaoistEconomics-ShanghaiTextbook-Lotta-OCR-sm.pdf",99,"Maoist Economics - Shanghai Textbook (duplicate)","English","Political economy","Duplicate copy."),
("Political/MAO/New democracy part 1.pdf",3,"নয়া গণতন্ত্র, ১ম পর্ব - মাও সেতুং (On New Democracy, Part 1)","Bengali","Political theory","Bengali edition of Mao's On New Democracy, part 1."),
("Political/MAO/mao-selected-military-writings-1963.pdf",3,"Selected Military Writings of Mao Tse-tung (1963)","English","Political theory","Mao's selected military writings (Peking, 1963)."),
("Political/MAO/ঐতিহাসিক চীন বিপ্লব.pdf",99,"ঐতিহাসিক চীন বিপ্লব (duplicate)","Bengali","History","Duplicate copy."),
("Political/MAO/নয়াগণতন্ত্র প্রসঙ্গে.pdf",99,"নয়াগণতন্ত্র প্রসঙ্গে (duplicate)","Bengali","Political theory","Duplicate copy."),
("Political/MAO/মাও রচনাবলী ১ ২ ৩.pdf",3,"মাও সে-তুং নির্বাচিত রচনাবলী ১-৩ (Selected Works of Mao Zedong, Vols 1-3)","Bengali","Political theory","Bengali edition of the Selected Works of Mao Zedong, volumes 1-3."),
("Political/MAO/মাও রেডবুক.pdf",99,"মাও রেডবুক (duplicate)","Bengali","Political theory","Duplicate copy of the Little Red Book."),
("Political/MAO/মাও_অনুশীলন_ও_দ্বন্দ্ব_ (1).pdf",99,"মাও অনুশীলন ও দ্বন্দ্ব (duplicate)","Bengali","Political theory","Duplicate copy."),
("Political/Marxism-Leninism-Maoism/s01-basic-course-revised-14th-printing.pdf",3,"Marxism-Leninism-Maoism Basic Course (Revised) - CPI (Maoist)","English","Political education","The MLM Basic Course study text (FLP edition)."),
("Political/Others/অরণ্য কন্যা.pdf",11,"অরণ্য কন্যা (Daughter of the Forest)","Bengali","Novel","Bengali novel set among forest and adivasi life."),
("Political/Others/গ্রামে_চলো_স্বর্ণ_মিত্র.pdf",4,"গ্রামে চলো - স্বর্ণ মিত্র (Go to the Villages)","Bengali","Politics","Swarna Mitra's Bengali call to revolutionary village work."),
("Political/Others/চারু_মজুমদার_রচনা_সংগ্রহ.PDF",4,"চারু মজুমদার রচনা সংগ্রহ (Collected Writings of Charu Majumdar)","Bengali","Politics","Collected writings of Charu Majumdar, founder of CPI(ML)."),
("Political/Others/সমাজ_ও_সভ্যতার_ক্রমবিকাশ_।।_রেবতী_বর্মণ.pdf",1,"সমাজ ও সভ্যতার ক্রমবিকাশ - রেবতী বর্মণ (Evolution of Society and Civilisation)","Bengali","Marxist theory","Rebati Barman's Bengali primer on historical materialism."),
("Political/Siraj_Sikder/কমরেড সিরাজ সিকদার এবং পেয়ারবাগান যুদ্ধের রাজনীতি- ইবনে মমতাজ (1).pdf",13,"কমরেড সিরাজ সিকদার এবং পেয়ারাবাগান যুদ্ধের রাজনীতি - ইবনে মমতাজ","Bengali","History","Ibne Momtaz on Siraj Sikder and the politics of the Peyarabagan armed struggle."),
("Political/Siraj_Sikder/সিরাজ_সিকদার_রাজনৈতিক_রচনা_সংকলন (1).pdf",13,"সিরাজ সিকদার রাজনৈতিক রচনা সংকলন (Collected Political Writings of Siraj Sikder)","Bengali","Politics","Collected political writings of Siraj Sikder, founder of the Purba Banglar Sarbahara Party."),
("@peopleslibrary_the-dark-web-for-the-rational.pdf",15,"The Dark Web for the Rational - linkcabin","English","Cybersecurity","Plain-language guide to understanding and navigating the dark web."),
("@peopleslibrary_অপ্রকাশিত_মরিচঝাঁপি.pdf",5,"অপ্রকাশিত মরিচঝাঁপি (Marichjhapi - The Untold Story)","Bengali","History","Bengali account of the 1979 Marichjhapi massacre of Dalit refugees in the Sundarbans."),
]

# ---- Marx-Engels Collected Works (Vols 1-50) ----
MECW = {
 "Marx & Engels Collected Works Volume 1_ Ka - Karl Marx.pdf":(1,"Marx 1835-1843"),
 "Marx & Engels Collected Works Volume 2_ Fr - Karl Marx.pdf":(2,"Engels 1838-1842"),
 "Marx & Engels Collected Works Volume 3_ Ka - Karl Marx.pdf":(3,"Marx 1843-1844 (incl. 1844 Manuscripts)"),
 "Marx_&_Engels_Collected_Works_Volume_4_Ma_Karl_Marx_1.pdf":(4,"Marx and Engels 1844-1845 (The Holy Family)"),
 "Marx & Engels Collected Works Volume 5_ Ma - Karl Marx.pdf":(5,"1845-1847 (The German Ideology)"),
 "Marx & Engels Collected Works Volume 6_ Ma - Karl Marx.pdf":(6,"1845-1848 (Poverty of Philosophy)"),
 "Marx_&_Engels_Collected_Works_Volume_7_Ma_Karl_Marx_1.pdf":(7,"1848 (The Communist Manifesto era)"),
 "Marx & Engels Collected Works Volume 8_ Ma - Karl Marx.pdf":(8,"1848-1849"),
 "Volume 9.pdf":(9,"1849"),
 "Volume 10.pdf":(10,"1849-1851"),
 "Volume 11.pdf":(11,"1851-1853 (18th Brumaire)"),
 "Volume 12.pdf":(12,"1853-1854"),
 "Volume 13.pdf":(13,"1854-1855"),
 "Volume 14.pdf":(14,"1855-1856"),
 "Volume 15.pdf":(15,"1856-1858"),
 "Volume 16.pdf":(16,"1858-1860"),
 "Volume 17.pdf":(17,"1859-1860"),
 "Volume 18.pdf":(18,"1857-1862"),
 "Volume 19.pdf":(19,"1861-1864"),
 "Volume 20.pdf":(20,"1864-1868"),
 "Volume 21.pdf":(21,"1867-1870"),
 "Volume 22.pdf":(22,"1870-1871 (The Civil War in France)"),
 "Volume 23.pdf":(23,"1871-1874"),
 "Volume 24.pdf":(24,"1874-1883 (Critique of the Gotha Programme)"),
 "Volume 25.pdf":(25,"Engels (Anti-Duhring, Dialectics of Nature)"),
 "Volume 26.pdf":(26,"Engels 1882-1889 (Origin of the Family)"),
 "Volume 27.pdf":(27,"Engels 1890-1895"),
 "Volume 28.pdf":(28,"Marx 1857-1861 (Economic Manuscripts)"),
 "Volume 29.pdf":(29,"Marx 1857-1861"),
 "Volume 30.pdf":(30,"Marx 1861-1863"),
 "Volume 31.pdf":(31,"Marx 1861-1863"),
 "Volume 32.pdf":(32,"Marx 1861-1863"),
 "Volume 33.pdf":(33,"Marx 1861-1863"),
 "Volume 34.pdf":(34,"Marx 1861-1864"),
 "Volume 35.pdf":(35,"Capital, Volume I"),
 "Volume 36.pdf":(36,"Capital, Volume II"),
 "Volume 37.pdf":(37,"Capital, Volume III"),
 "Volume 38.pdf":(38,"Letters 1844-1851"),
 "Volume 39.pdf":(39,"Letters 1852-1855"),
 "Volume 40.pdf":(40,"Letters 1856-1859"),
 "Volume 41.pdf":(41,"Letters 1860-1864"),
 "Volume 42.pdf":(42,"Letters 1864-1868"),
 "Volume 43.pdf":(43,"Letters 1868-1870"),
 "Volume 44.pdf":(44,"Letters 1870-1873"),
 "Volume 45.pdf":(45,"Letters 1874-1879"),
 "Volume 46.pdf":(46,"Letters 1880-1883"),
 "Volume 47.pdf":(47,"Letters 1883-1886"),
 "Volume 48.pdf":(48,"Letters 1887-1890"),
 "Volume 49.pdf":(49,"Letters 1890-1892"),
 "Volume 50.pdf":(50,"Letters 1892-1895"),
}
for fn,(vol,period) in MECW.items():
    title = "Marx-Engels Collected Works, Vol. %02d - %s" % (vol, period)
    E.append((fn,2,title,"English","Marxist theory","Volume %d of the 50-volume Lawrence and Wishart Collected Works of Marx and Engels." % vol))

# ---------- filename sanitiser ----------
def san(name):
    name = name.replace(":"," -").replace("/"," ").replace("\\"," ")
    name = re.sub(r'[*?"<>|]', "", name)
    name = re.sub(r"\s+", " ", name).strip().strip(".")
    if len(name) > 145:
        name = name[:145].rstrip()
    return name

# load page counts (normalise keys)
def nfc(s): return unicodedata.normalize("NFC", s)
meta = {nfc(m["rel"]): m.get("npages",0) for m in json.load(open(r"d:/READING/meta_report.json","r",encoding="utf-8"))}

# index actual files by NFC-normalised relpath so Bengali NFC/NFD mismatches resolve
actual_index = {}
for root, dirs, files in os.walk(BASE):
    for f in files:
        if f.lower().endswith(".pdf"):
            ap = os.path.join(root, f)
            arel = os.path.relpath(ap, BASE).replace(os.sep, "/")
            actual_index[nfc(arel)] = ap

# ---------- perform moves ----------
records = []   # (cat, title, lang, genre, desc, newrel, pages)
missing = []
for rel, cat, title, lang, genre, desc in E:
    src = actual_index.get(nfc(rel))
    if not src or not os.path.exists(src):
        missing.append(rel); continue
    folder = CATS[cat]
    newname = san(title) + ".pdf"
    dstdir = os.path.join(BASE, folder)
    os.makedirs(dstdir, exist_ok=True)
    dst = os.path.join(dstdir, newname)
    n = 2
    while os.path.exists(dst) and os.path.abspath(dst) != os.path.abspath(src):
        dst = os.path.join(dstdir, san(title) + (" (%d)" % n) + ".pdf"); n += 1
    if os.path.abspath(dst) != os.path.abspath(src):
        shutil.move(src, dst)
    newrel = os.path.relpath(dst, BASE).replace(os.sep, "/")
    records.append((cat, title, lang, genre, desc, newrel, meta.get(nfc(rel),0)))

# detect any leftover pdfs not in catalog
leftover = []
for root, dirs, files in os.walk(BASE):
    for f in files:
        if f.lower().endswith(".pdf"):
            p = os.path.relpath(os.path.join(root,f), BASE).replace(os.sep,"/")
            top = p.split("/")[0]
            if top not in CATS.values():
                leftover.append(p)

json.dump({"records":records,"missing":missing,"leftover":leftover},
          open(r"d:/READING/catalog_result.json","w",encoding="utf-8"), ensure_ascii=False, indent=1)
print("moved:",len(records),"missing:",len(missing),"leftover:",len(leftover))
print("MISSING:",missing[:20])
print("LEFTOVER:",leftover[:40])
